### ISSUE TITLE
Falsely reporting error code 15: installed version is newer than one supplied, upgrade script stops with no changes

### ISSUE THREAD

**Issue by rdecaneva** [resilio-inc/connect-scripts#51]
### Issue
When upgrading the resilio agents from `v3.1.10009.2164` to `v3.1.5.1962`, the script incorrectly reports that the installed version is newer. 

### Steps to Reproduce
Following [this](https://connect.resilio.com/hc/en-us/articles/360004845800-Updating-Resilio-Agents-using-Distribution-Job) article to upgrade agents remotely.

### Possible Solution
I found that because the `build` version is not padded, the script believed that `10009` was greater than `5`. I added 0's to pad the build number. 
```
 ######### Check 4 - checking the agent version
Write-Verbose "Checking Agent versions..." 
...
## ADDED SECTION
$build_newVer=[string]$newversion.build
$build_oldVer=[string]$oldversion.build

$update_oldVer=[System.Version]::new($oldVer.Major,$oldVer.Minor,$build_oldVer.PadRight(5,'0'),$oldVer.Revision)
$update_newVer=[System.Version]::new($newVer.Major,$newVer.Minor,$build_newVer.PadRight(5,'0'),$newVer.Revision) 

if ($update_oldVer -gt $update_newVer) 
...
```

Probably a better way to handle this, but the above worked for me.

**Comment by sjel** [comment]
Fixed.
